### ISSUE TITLE
Filter by date-driven labels

### ISSUE THREAD

**Issue by stackpr** [brainite/glance#7]
Hide "idle-10" until October, and then highly prioritize it. This can be done statically by providing some basic variables that can be used within labels.

``` yaml
- filter: label:idle-{{month}}
  weight: 5
- filter: label:idle-{{month_1}}
  weight: 0
```
